[package]
name = "swaptrade_contract"
version = "0.1.0"
cairo-version = "2.11.4"
edition = "2023_11"

[dependencies]
starknet = "2.11.4"

[dev-dependencies]
cairo_test = "2.11.4"

[lib]
path = "src/lib.cairo"

[tool.starknet-contract]
casm = true

[tool.starknet-test]
test-path = "tests"

